clean:
  drop_columns: [weight, payer_code, examide, citoglipton]
  expired_hospice_ids: [11, 13, 14, 19, 20, 21]
  fill_unknown_columns: [race, medical_specialty, diag_1, diag_2, diag_3]
  id_columns: [admission_type_id, discharge_disposition_id, admission_source_id]
  keep_first_encounter_only: false  # false = keep all rows, do a group split later